name: "My First Workflow"

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: echo
              run: echo "SHIVA"
            - name: checkout repo
              uses: actions/checkout@v4
            - name: os
              run: |
                cat /etc/os-release
                ls
                pwd
                lsblk
                lscpu
                free -m 